# Generated by Django 5.x on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):
    """Делает поле краткого описания энциклопедии необязательным."""

    dependencies = [
        ("content", "0002_encyclopediaarticle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encyclopediaarticle",
            name="summary",
            field=models.CharField(blank=True, max_length=255, verbose_name="Краткое описание"),
        ),
    ]
