# Generated by Django 5.2.7 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    """Добавляет в аналитический промт настраиваемый лимит токенов ответа LLM."""

    dependencies = [
        ("content", "0003_alter_encyclopedia_summary_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisprompt",
            name="max_tokens",
            field=models.PositiveIntegerField(default=1000, verbose_name="Лимит токенов ответа"),
        ),
    ]
